In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"C:\Users\valen\PRACTICA_PARCIAL\practice_herramientas_dataset.csv")

In [ ]:
df.shape #Contamos la forma del dataset

In [ ]:
df["City"] = df["City"].astype(str)
"""
Convertimos una columna a tipo str
"""

In [ ]:
df["Order_ID"] = df["Order_ID"].astype(float)
"""
Convertimos una columna a tipo str
"""

In [ ]:
df.dtypes #Estudiar que tipos de datos tenemos

In [ ]:
df[["Customer","City","Category"]] #Hacer una vista de col

In [ ]:
df.head() #Vista previa del df 5 primeras filas

In [ ]:
df = df.set_index("City") #Convertir en indice una col

In [ ]:
prueba = df.loc["Salto"] #mostramos filas que contengan salto

In [ ]:
prueba.head()

In [ ]:
df["City"].unique().tolist() #listado de ciudades que aparecen en df

In [ ]:
df.iloc[75] #te muestra la fila indicada del df o fila y col

In [ ]:
df.info() #te permite analizar la estructura de filas

In [ ]:
df["Order_Amount"].describe() #datos estadisticos de col

In [ ]:
df["City"].value_counts() #Cuenta cantidad de ocurrencias de un valor con normalize=true muestra %

In [ ]:
df["City"] = df["City"].replace("Montevideo", "MVD")


In [ ]:
prueba2 = df["City"] == "Colonia" ##mostramos filas que contengan COLONIA sin crear indice
top5 = df[prueba2].head()
top5

In [ ]:
df["Order_Amount"].plot.line()


In [ ]:
df.tail(10) #te muestra los ultimos valores

In [ ]:
df.columns = ['GAY','HOLA','PUTO','TR','SA','OPA']

In [ ]:
df["Order_Amount"].isnull() #Diferentes formas de ver valores null

In [ ]:
df[df["Order_Amount"].isnull()]

In [ ]:
df.dropna(how="any",inplace=True) #dropea las filas con por lo menos un valor null , con inplace lo reemplaza en el df original, sino solo muestra

In [ ]:
df.fillna(10,inplace=True) #reemplaza el valor null por el indicado, inplace para dejarlo en el df

In [ ]:
df.tail()

In [ ]:
df["Order_Amount"] = df["Order_Amount"].fillna(df["Order_Amount"].mean()) #reemplaza el valor null por la media

In [ ]:
df.rename(columns={"Order_Amount":"Value_Amount"}, inplace=True)

In [ ]:
df[df["Value_Amount"]>1285,] #te muestra valores mayores a x

In [ ]:
df.sort_values("City", ascending=False) #te ordena por orden descendente una columna

In [ ]:
df.groupby(["Order_ID","Value_Amount"])

In [ ]:
df

In [ ]:
df.groupby("City")["Order_Amount"].mean()


In [ ]:
df["Order_Amount"].apply(lambda x: x / 41)

In [ ]:
df2 = pd.read_csv(r"C:\Users\valen\PRACTICA_PARCIAL\dataset_nuevo.csv")

In [ ]:
df2

In [ ]:
df = pd.concat([df, df2], ignore_index=True)


In [ ]:
df

In [ ]:
df["Order_Date"] = df["Order_Date"].fillna(df["Date"]) #fillna cambia los valores null por lo que le indiques
df.drop(columns="Date",inplace=True)

# Práctica de Numpy


In [ ]:
ds = pd.read_csv(r"C:\Users\valen\PRACTICA_PARCIAL\dataset_numpy_practice.csv")

In [ ]:
ds

In [ ]:
gay = np.linspace(0,100,6)

In [ ]:
gay

In [ ]:
puto = np.arange(0,13,3)

In [ ]:
puto

In [ ]:
pitudo = np.full((2,3), 8)

In [ ]:
pitudo

In [ ]:
manza_gay = np.random.rand(2,4)*100 #te hace un array random de dimensiones 2x4 con float del 0 al 100
manza_gay

In [ ]:
vale_capo = np.random.randint(100, size=(2,4)) #lo mismo pero con enteros
vale_capo

In [ ]:
vale_capo.size
vale_capo.tolist()

In [ ]:
np.copy(manza_gay)

In [ ]:
pitudo.flatten()

In [ ]:
manza_gay.T

In [ ]:
manza_gay.reshape(2,4)

In [ ]:
nuevo = np.resize(manza_gay, (3,5))

In [ ]:
nuevo

In [ ]:
np.insert(nuevo,7,10)


In [ ]:
np.delete(nuevo, 0 , axis =1)

In [ ]:
nuevo[2,3]

In [ ]:
nuevo[1,3] = 5

In [117]:
nuevo

array([[17.14801358, 33.41122983, 50.52496955, 65.40856843, 12.93458426],
       [ 4.        ,  4.        ,  4.        ,  5.        ,  4.        ],
       [50.52496955, 65.40856843, 12.93458426, 42.83021766, 77.15176561]])

In [118]:
nuevo[0:2,3]

array([65.40856843,  5.        ])

In [119]:
nuevo < 50

array([[ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True, False]])